# Generated by Django 5.1.2 on 2026-02-12 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colaboradores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Biometria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encoding', models.BinaryField()),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('posicao', models.IntegerField(choices=[(0, 'Inativo'), (1, 'Ativo')], default=1)),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biometrias', to='colaboradores.colaborador')),
            ],
            options={
                'verbose_name': 'Biometria',
                'verbose_name_plural': 'Biometrias',
            },
        ),
    ]
